### ISSUE TITLE
How to run demo code

### ISSUE THREAD

**Issue by anas-zafar** [ChengShiest/Zip-Your-CLIP#1]
Thank you for the amazing work! Can you please guide how can I run demo code? Thanks

**Comment by ChengShiest** [comment]
Hi, after successfully installing [clip_surgery](https://github.com/xmed-lab/CLIP_Surgery) the folder should look like
```text
Zip-Your-CLIP/
├── Clip_surgery
├── demo.ipynb
```
You can then test follow readme and demo.ipynb
